### ISSUE TITLE
Can docker set the order of start up?

### ISSUE THREAD

**Issue by fils** [nein09/polder-federated-search#1]
@nein09 

So, if I follow, these lines

https://github.com/nein09/polder-federated-search/blob/e8a8ef9c06f338dc10272d4e0b4e0224853f1ccc/docker/docker-compose.yaml#L3-L14

This will start up Gleaner with the -setup call to ensure its requested top level bucket exists. 

However, if Minio is not yet started, there may be no object store to talk to yet?   Assuming it is the one you are using.  

Is there a way to sequence how containers start in Docker?

**Comment by fils** [comment]
ha!  I didn't even see the depends on!   Thanks.  I didn't know about that one!

**Comment by nein09** [comment]
oh yeah! I just found out about that today. It looks handy.

There's a tradeoff there, where you can't use `extends` if you have 'depends on', which is why the docker-compose file repeats itself. But the 'depends on' looked worth it.
